# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0003_remove_department_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
