# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='staff',
        ),
    ]
