# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0001_initial'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='announcement_groups', to='rbac.Group'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='announcement_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
