# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250)),
                ('filepath', models.CharField(default='', max_length=255)),
                ('creation_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('action_upon_expiry', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Archive'), (2, 'Delete')], default=0)),
                ('metadata', models.TextField(default='')),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('extension', models.CharField(max_length=50)),
                ('version', models.FloatField(default=1.0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('thumbnail', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='tempfiles')),
                ('name', models.CharField(max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail')),
                ('extension', models.CharField(max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attached', models.BooleanField(default=False)),
            ],
        ),
    ]
