# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
        ('category', '0002_auto_20170314_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprepository',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkedfiles',
            name='attach_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkedfiles',
            name='linkfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedfile', to='documents.Documents'),
        ),
        migrations.AddField(
            model_name='linkedfiles',
            name='sourcefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcefile', to='documents.Documents'),
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AddField(
            model_name='documents',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lockedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documents',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Documents'),
        ),
        migrations.AddField(
            model_name='documents',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documents',
            name='version_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='documents.Documents'),
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together=set([('parent', 'version')]),
        ),
    ]
