# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170319_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='filename',
            field=models.FilePathField(max_length=250, path='/workflow/media/'),
        ),
    ]
