# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20170319_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='filename',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='documents',
            name='filepath',
            field=models.FilePathField(max_length=255, path='/workflow/media/'),
        ),
    ]
