# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_auto_20170319_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
