# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20170320_1403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together=set([('parent', 'version', 'deleted_at')]),
        ),
    ]
