# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20170406_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temprepository',
            name='extension',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
