# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20170613_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='extension',
            field=models.CharField(max_length=500),
        ),
    ]
