# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20170614_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='filepath',
            field=models.FileField(upload_to='repository'),
        ),
    ]
