# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20170620_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='filepath',
            field=models.FilePathField(max_length=255, path='/workflow/media/'),
        ),
    ]
