# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20170621_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprepository',
            name='excel_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
