# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-06 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_downloadsearchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='pages',
            field=models.BigIntegerField(null=True),
        ),
    ]
