# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-11 08:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_documents_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='metadata_json_index',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
