# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-12 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_documents_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(blank=True, max_length=200, null=True)),
                ('DocumentType', models.IntegerField(blank=True, null=True)),
                ('doccreated', models.DateTimeField(blank=True, null=True)),
                ('docexpired', models.DateTimeField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
