# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-11 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_documents_metadata_json_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='metadata_json_index',
        ),
    ]
