# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-12 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_savesearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesearch',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
