# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-11 11:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_remove_documents_metadata_json_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDocumentJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
