# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20171212_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesearch',
            name='search_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
