# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-12 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_metadocumentjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadocumentjson',
            name='doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_id', to='documents.Documents'),
        ),
    ]
