# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20171212_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesearch',
            name='doccreated',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='savesearch',
            name='docexpired',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
