# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-12 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20171212_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesearch',
            name='doccreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savesearch',
            name='docexpired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savesearch',
            name='metadata',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='savesearch',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
