# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20171212_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesearch',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savesearch',
            name='match',
            field=models.BooleanField(default=False),
        ),
    ]
