# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-18 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_auto_20171213_1207'),
        ('documents', '0020_documents_edited_by'),
    ]

    operations = [
    ]
