# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0024_merge_20171217_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='watermark',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Approved'), ('2', 'Classified'), ('3', 'Confidential'), ('4', 'Rejected')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='documents',
            name='watermark_file_path',
            field=models.FilePathField(blank=True, max_length=255, null=True, path='/workflow/media/'),
        ),
        migrations.AddField(
            model_name='documents',
            name='watermarked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watermarkedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
