# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_auto_20171217_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMarkFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='watermark')),
            ],
        ),
    ]
