# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_watermarkfiles_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='watermark',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Approved'), ('2', 'Classified'), ('3', 'Confidential'), ('4', 'Rejected'), ('5', 'Free Text')], default=0, max_length=50),
        ),
    ]
