# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-23 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_auto_20171218_1131'),
        ('documents', '0014_temprepository_excel_file_path'),
    ]

    operations = [
    ]
