# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_merge_20171223_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='watermarked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
