# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-26 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_documents_watermarked_at'),
        ('documents', '0024_merge_20171218_1016'),
    ]

    operations = [
    ]
