# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-28 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_merge_20171226_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='box_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='shelf_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
