# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_auto_20171228_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='box_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='shelf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
