# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0033_auto_20171228_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='redacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redactedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documents',
            name='redacted_user',
            field=models.ManyToManyField(blank=True, related_name='redacted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
