# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-03 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_documents_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='source',
            field=models.CharField(default='dms', max_length=20),
        ),
    ]
