# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_auto_20180104_1555'),
        ('documents', '0034_auto_20180103_1049'),
    ]

    operations = [
    ]
