# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-03 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0022_merge_20180102_1556'),
        ('documents', '0035_auto_20180103_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='app_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn.Application'),
        ),
    ]
