# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-03 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_documents_app_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='app_id',
            new_name='app',
        ),
    ]
