# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_merge_20180104_1702'),
        ('documents', '0037_auto_20180103_1505'),
    ]

    operations = [
    ]
