# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_activity', '0002_dmsactivity_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsactivity',
            name='filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
