# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_documents_edited_by'),
        ('dms_activity', '0004_remove_dmsactivity_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsactivity',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Documents'),
        ),
    ]
