# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('published', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocTypePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MetaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name contains alphanumeric, underscore. Length: 3 to 50', regex='[-a-zA-Z0-9_]{3,50}$')])),
                ('displayname', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Display contains alphanumeric, underscore and space. Length: 3 to 100', regex='[-a-zA-Z0-9_ ]{3,100}$')])),
                ('data_type', models.PositiveSmallIntegerField(choices=[(0, 'String'), (1, 'Integer'), (2, 'TextArea'), (3, 'DropDown'), (4, 'Date'), (5, 'Float')], default=0)),
                ('default_text', models.CharField(blank=True, max_length=250, null=True)),
                ('required', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'YES')], default=0)),
                ('order', models.PositiveSmallIntegerField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
