# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctypepermission',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Group'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='metafield',
            unique_together=set([('doc', 'order'), ('doc', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='doctypepermission',
            unique_together=set([('doc', 'groups')]),
        ),
    ]
