# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170314_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafield',
            name='max',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='metafield',
            name='min',
            field=models.IntegerField(default=5),
        ),
    ]
