# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20170327_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafield',
            name='max',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='metafield',
            name='min',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
