# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20170328_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctypepermission',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permission', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='doctypepermission',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctype_groups', to='rbac.Group'),
        ),
    ]
