# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20170328_1628'),
        ('category', '0012_auto_20170329_1841'),
    ]

    operations = [
    ]
