# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_merge_20170402_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafield',
            name='unique',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'YES')], default=0),
        ),
    ]
