# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_metafield_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metafield',
            name='displayname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
