# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_auto_20171220_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='retention_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='retention_policy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Archive'), (2, 'Delete')], default=0),
        ),
    ]
