# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_auto_20171227_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafield',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
