# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
