# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 05:58
from __future__ import unicode_literals

import apps.core.rbac.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(default=apps.core.rbac.models.default_expiry_date),
        ),
    ]
