# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_staff'),
        ('rbac', '0003_auto_20170324_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
