# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 07:09
from __future__ import unicode_literals

import apps.core.rbac.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_user_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.rbac.models.signature_dir),
        ),
    ]
