# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20170508_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='rbac.Role'),
        ),
    ]
