# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20170906_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active'), ('2', 'Vacation'), ('3', 'Expired')], default=1, max_length=50),
        ),
    ]
