# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-07 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20170906_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDelegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(verbose_name='end_date')),
                ('absent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_user', to=settings.AUTH_USER_MODEL)),
                ('present_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
