# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-11 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0018_commercial_condo_freehold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username contains alphanumeric, underscore and period(.). Length: 4 to 50', regex='[-a-zA-Z0-9_.]{4,50}$')], verbose_name='user name')),
                ('emailPhone', models.CharField(max_length=70, unique=True)),
                ('registration', models.IntegerField(choices=[(1, 'Registered'), (2, 'Unregistered')])),
            ],
        ),
    ]
