# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-12 08:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0019_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='source',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Email')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Username contains alphanumeric, underscore and period(.). Length: 4 to 50', regex='[-a-zA-Z0-9_.]{4,50}$')], verbose_name='user name'),
        ),
    ]
