# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-15 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0021_auto_20180313_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='unregistered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
