# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0023_appviewreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appviewreport',
            name='user',
        ),
        migrations.AddField(
            model_name='appviewreport',
            name='appuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Applogin_data', to='rbac.AppUser'),
        ),
    ]
