# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0024_auto_20180321_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Residential'), (2, 'Condo'), (3, 'Commercial')])),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Commercial')),
                ('condo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Condo')),
                ('freehold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Freehold')),
            ],
        ),
    ]
