# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0027_auto_20180325_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=470, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Resolved'), (2, 'Unresolved')])),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.AppUser')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.HouseLocation')),
            ],
        ),
        migrations.AlterField(
            model_name='favourites',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.HouseLocation'),
        ),
    ]
