# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0030_licensetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='appuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.AppUser'),
        ),
    ]
