# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0031_auto_20180415_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='source',
            field=models.CharField(blank=True, max_length=170),
        ),
    ]
