# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-15 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0033_auto_20180415_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('appuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AppUserlogin_data', to='rbac.AppUser')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.HouseLocation')),
            ],
        ),
    ]
