# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-28 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0035_emailtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='msg',
            field=models.CharField(blank=True, max_length=370, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
    ]
