# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-11 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0036_auto_20180528_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condo',
            name='Balcony',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='WaterFeatures2',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='WaterFeatures3',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='WaterFeatures4',
        ),
        migrations.RemoveField(
            model_name='condo',
            name='WaterFeatures5',
        ),
    ]
