# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0037_auto_20190411_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password_reset_request',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
    ]
