# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-24 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0038_appuser_password_reset_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='VirtualTourURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='condo',
            name='VirtualtourURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='freehold',
            name='VirtualtourURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
