# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 06:43
from __future__ import unicode_literals

import apps.workflow.bpmn.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0008_auto_20170508_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default=apps.workflow.bpmn.models.unique_id, max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'completed'), (1, 'todo'), (2, 'open')], default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.TextField()),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('delay', models.DateTimeField(blank=True, null=True)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_user', to=settings.AUTH_USER_MODEL)),
                ('init_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='init_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'completed'), (1, 'todo'), (2, 'open'), (3, 'non claimed'), (4, 'reassigned')])),
                ('init_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(db_index=True)),
                ('risk_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('index_pos', models.PositiveIntegerField(default=0)),
                ('routing_type', models.IntegerField(choices=[(0, 'sequential'), (1, 'parallel')], default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation', to='bpmn.Application')),
            ],
        ),
        migrations.CreateModel(
            name='EForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, null=True, unique=True)),
                ('reference_name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('location', models.FileField(upload_to=apps.workflow.bpmn.models.generated_document_dir)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Application')),
            ],
        ),
        migrations.CreateModel(
            name='InputDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=100)),
                ('file', models.FileField(default='', upload_to=apps.workflow.bpmn.models.input_doc_dir)),
                ('variable', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_input_doc', to='bpmn.Application')),
            ],
        ),
        migrations.CreateModel(
            name='OutputDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.BooleanField(default=False)),
                ('download', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('diagram', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assigned_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn.Category')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='project_supervisors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('name', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(max_length=50)),
                ('email', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, null=True, unique=True)),
                ('reference_name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'eForm'), (1, 'script'), (2, 'output_document')])),
                ('condition', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('mode', models.IntegerField(choices=[(0, 'edit'), (1, 'view')])),
                ('eform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn.EForm')),
                ('output_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn.OutputDocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project')),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('element_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('name', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(default=24)),
                ('delay', models.CharField(blank=True, max_length=4, null=True)),
                ('time_unit', models.CharField(blank=True, choices=[('0', 'hour'), ('1', 'day'), ('2', 'week'), ('3', 'month')], default=1, max_length=10)),
                ('alert', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.BooleanField(default=False)),
                ('assignment_type', models.IntegerField(choices=[(0, 'cyclic assignment'), (1, 'manager assignment'), (2, 'manual assignment'), (3, 'self service')], default=0)),
                ('rules_applied', models.BooleanField(default=False)),
                ('group', models.ManyToManyField(blank=True, to='rbac.Group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project')),
                ('user', models.ManyToManyField(blank=True, related_name='users_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_based_rules', to='bpmn.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('datetime', 'datetime'), ('grid', 'grid'), ('array', 'array'), ('file', 'file')], max_length=120)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('default', models.TextField(blank=True, null=True)),
                ('accepted_defaults', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='bpmn.Project')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='bpmn.Task'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='bpmn.Task'),
        ),
        migrations.AddField(
            model_name='route',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='bpmn.Task'),
        ),
        migrations.AddField(
            model_name='outputdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project'),
        ),
        migrations.AddField(
            model_name='outputdocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Template'),
        ),
        migrations.AddField(
            model_name='inputdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_input_doc', to='bpmn.Project'),
        ),
        migrations.AddField(
            model_name='inputdocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_input_doc', to='bpmn.Task'),
        ),
        migrations.AddField(
            model_name='inputdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegation_sent_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_delegations', to='bpmn.Task'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project'),
        ),
        migrations.AddField(
            model_name='appcomment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_comment', to='bpmn.Application'),
        ),
        migrations.AddField(
            model_name='appcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Task'),
        ),
        migrations.AddField(
            model_name='appcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('project', 'file_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('position', 'task')]),
        ),
        migrations.AlterUniqueTogether(
            name='outputdocument',
            unique_together=set([('project', 'title'), ('project', 'generated_name')]),
        ),
    ]
