# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0002_weekend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekend',
            old_name='days',
            new_name='day',
        ),
    ]
