# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-13 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0008_appquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='appquery',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
