# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0010_auto_20171113_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='appquery',
            name='query_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
