# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0012_appquery_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='additional_status',
            field=models.IntegerField(blank=True, choices=[(0, 'reject'), (1, 'recheck')], null=True),
        ),
    ]
