# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0013_delegation_additional_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recheck',
            field=models.IntegerField(choices=[(0, 'flow forward'), (1, 'resume forward')], default=0),
        ),
    ]
