# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-20 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0014_project_recheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='recheck',
            field=models.IntegerField(choices=[(1, 'flow forward'), (2, 'resume forward')], default=0),
        ),
    ]
