# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0016_auto_20171120_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='sent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_task_delegations', to='bpmn.Task'),
        ),
    ]
