# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0017_delegation_sent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='is_recheck',
            field=models.BooleanField(default=False),
        ),
    ]
