# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-04 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0018_delegation_is_recheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='eform',
            name='variables_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
