# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-02 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0021_application_out_open'),
        ('bpmn', '0021_auto_20180102_1529'),
    ]

    operations = [
    ]
