# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-23 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bpmn', '0022_merge_20180102_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktrackRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtrack_path', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Application')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Project')),
            ],
        ),
        migrations.CreateModel(
            name='EformHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='appquery',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpmn.Delegation'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='actual_task_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegation',
            name='is_delegated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eformhistory',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmn.Delegation'),
        ),
    ]
